language: perl

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - "sudo pip install requests"
    - "cpanm Method::Signatures"
    - "cpanm Expect"
    - "cpanm Term::ReadLine::Perl5"
    - "cpanm --mirror http://cpan.cpantesters.org/ FindBin::libs"
    - "cpanm Test::BDD::Cucumber"

script: make test
