language: perl

perl:
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - sudo apt-get install mailx

install:
    - "sudo pip install requests"
    - "cpanm Method::Signatures"
    - "cpanm Expect"
    - "cpanm Term::ReadLine::Perl5"
    - "cpanm HTTP::Request::Common"
    - "cpanm FindBin::libs"
    - "cpanm Capture::Tiny"
    - "cpanm Test::BDD::Cucumber"

script: make test

after_failure: mailx -s "Hannover Hotspots install log" paultcochrane@gmail.com < /home/travis/.cpanm/work/*/build.log
