name: Unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.38', '5.36', '5.34']
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: cpanm --installdeps --with-develop --notest .
      - run: |
          perl Makefile.PL
          make
          make test
